### ISSUE TITLE
Tweak not working at all

### ISSUE THREAD

**Issue by ki-tty** [tomaszpoliszuk/MagSafeController#5]
iPhone 8, iOS 13.5, jailbroken with odysseyra1n.
Tweak is enabled in preferences but upon starting charging, the magsafe animation does not show up.
I'm not sure if it's a tweak conflicting, the tweak not working on non-notched devices, or if it could be something about libhooker, but I've provided a tweaklist if it helps: https://pastebin.com/ZgUqWPzq (Made after I uninstalled the tweak, but it was in fact installed while I tested it)

Definitely my bad if it says somewhere that it doesn't work on non-notched devices and I missed it, or if it's just user error.
If you need more info to diagnose the issue, I'd be happy to provide it.

**Comment by tomaszpoliszuk** [comment]
It was created on non-notched devices so that's not the issue - I'll review that tweak list later but before I do - maybe some of those tweaks have option to disable battery view while connecting to charger?

Additionally could you install it again, open iCleaner Pro, go to Cydia Substrate Addons (here make sure that you have "Automatically manage dependencies"), tap "all" to disable all tweaks and then enable only "MagSafe Controller" (required dependencies will automatically turn on), tap on apply and then test if it works (if do then it's indeed conflic with some other tweak, unless some of them turns off battery view while connecting to charger but that's covered in first question).

**Comment by ki-tty** [comment]
It turned out to be Lynx, I had battery view disabled, which I had done so long ago that I totally forgot about it. Thanks for helping me troubleshoot!

**Comment by tomaszpoliszuk** [comment]
Awesome - so I'm closing this issue because it doesn't exist :)

Have a nice day!
